version: "3.1"

services:
  sopapi:
    image: sopapi:latest
    container_name: sopapi
    networks:
      - sandbixproxy_mynet
    environment:
      - POSTGRES_USER=${SOPAPI_POSTGRES_USER}
      - POSTGRES_SECRET=${SOPAPI_POSTGRES_SECRET}
      - POSTGRES_HOST=${SOPAPI_POSTGRES_HOST}
      - POSTGRES_DB=${SOPAPI_POSTGRES_DB}
      - TWITCH_ID=${SOPAPI_TWITCH_ID}
      - TWITCH_SECRET=${SOPAPI_TWITCH_SECRET}
      - BASE_URL=${SOPAPI_BASE_URL}
      - FRONT_BASE_URL=${SOPAPI_FRONT_BASE_URL}
      - ORIGINS=${SOPAPI_ORIGINS}

networks:
  sandbixproxy_mynet:
    external: true