version: "3.1"

services:
  sopapi:
    image: sopapi:latest
    container_name: sopapi
    networks:
      - sandbixproxy_mynet
    environment:
      - POSTGRES_USER=${SOPAPI_POSTGRES_USER}
      - POSTGRES_SECRET=${SOPAPI_POSTGRES_SECRET}
      - POSTGRES_HOST=${SOPAPI_POSTGRES_HOST}
      - POSTGRES_DB=${SOPAPI_POSTGRES_DB}

networks:
  sandbixproxy_mynet:
    external: true